import { Text, Container, Graphics, Sprite, FillGradient } from 'pixi.js';
import type { Texture } from 'pixi.js';
import { GlowFilter } from 'pixi-filters';
import { gsap } from 'gsap';
import { BaseScene } from './BaseScene';
import { GameConfig } from '../config/GameConfig';
import { gameStore } from '../state/GameState';
import { SceneManager } from '../managers/SceneManager';
import { AssetManager } from '../managers/AssetManager';
import { MenuScene } from './MenuScene';

/**
 * GameScene7 — Slot 7: "Crystal Mines"
 * -------------------------------------
 * Stake-style mines in a glowing crystal cavern. 5×5 grid of sealed tiles —
 * each safe pick uncovers a gem and ratchets the multiplier up the fair-odds
 * ladder; hit a bomb and the round is lost. Cash out any time.
 *
 * Rich-graphics layer (all generated by tools/gen-art.mjs):
 *  - painted cavern background with glowing crystal clusters (mines-bg.png)
 *  - 3D tile backs, faceted gem and glossy bomb art (m_tile/m_gem/m_bomb.png)
 *  - 3D card-flip reveals, gem sparkle bursts + glow rings
 *  - bomb: chain reveal of every mine, explosion burst, shake, red flash
 *  - cash-out: gold coin fountain + banked banner
 */

const GRID = 5;
const CELLS = GRID * GRID;
const TILE = 138;
const GAP = 14;
const HOUSE_EDGE = 0.97;
const MINE_CHOICES = [3, 5, 10] as const;
const BET_STEPS = [1, 2, 5, 10, 20, 50, 100];

type Phase = 'idle' | 'playing' | 'done';

interface TileCell {
    root: Container;
    back: Container;
    front: Container;
    revealed: boolean;
    isBomb: boolean;
    index: number;
}

/** Fair multiplier after `k` safe picks with `m` mines (house-edged). */
function fairMult(k: number, m: number): number {
    let v = HOUSE_EDGE;
    for (let i = 0; i < k; i++) v *= (CELLS - i) / (CELLS - m - i);
    return v;
}

export class GameScene7 extends BaseScene {
    private readonly gridLayer = new Container();
    private readonly fxLayer = new Container();
    private readonly uiContainer = new Container();

    private readonly gridX = GameConfig.width / 2 - (GRID * TILE + (GRID - 1) * GAP) / 2;
    private readonly gridY = 150;

    private phase: Phase = 'idle';
    private mines = 5;
    private picks = 0;
    private bombs = new Set<number>();
    private tiles: TileCell[] = [];

    private textures = new Map<string, Texture>();
    private gemGlow!: GlowFilter;

    private headerText!: Text;
    private actionButton!: Graphics;
    private actionLabel!: Text;
    private actionSub!: Text;
    private betValueText!: Text;
    private balanceText!: Text;
    private banner!: Text;
    private redFlash!: Graphics;
    private readonly minePills: { pill: Graphics; label: Text; value: number }[] = [];
    private readonly sparkles: Graphics[] = [];
    private readonly boomParts: Graphics[] = [];
    private readonly coins: Graphics[] = [];

    private readonly onKeyDown = (e: KeyboardEvent): void => {
        if (e.code === 'Space') { e.preventDefault(); this.action(); }
        // (back-to-menu removed) if (e.code === 'Escape') SceneManager.switchScene(new MenuScene());
    };

    public async init(): Promise<void> {
        this.textures = await AssetManager.loadSymbols(['m_tile', 'm_gem', 'm_bomb']);
        this.addChild(await this.buildBackground());
        this.addChild(this.gridLayer);
        this.addChild(this.fxLayer);
        this.addChild(this.uiContainer);

        this.gemGlow = new GlowFilter({ distance: 18, outerStrength: 2.2, color: 0x7dffb0, quality: 0.2 });
        this.buildGrid();
        this.createUI();
        this.resetRound();
        window.addEventListener('keydown', this.onKeyDown);
    }

    public async start(): Promise<void> {}
    public update(_delta: number): void {}
    public resize(_width: number, _height: number): void {}

    public override async destroyScene(): Promise<void> {
        window.removeEventListener('keydown', this.onKeyDown);
        gsap.killTweensOf(this.position);
        for (const t of this.tiles) { gsap.killTweensOf(t.root.scale); gsap.killTweensOf(t.back.scale); gsap.killTweensOf(t.front.scale); }
        for (const pool of [this.sparkles, this.boomParts, this.coins]) for (const g of pool) gsap.killTweensOf(g);
        gsap.killTweensOf(this.banner);
        gsap.killTweensOf(this.banner.scale);
        gsap.killTweensOf(this.redFlash);
        await super.destroyScene();
    }

    // --- round flow ------------------------------------------------------------

    private action(): void {
        const state = gameStore.getState();
        if (this.phase === 'idle') {
            if (state.balance < state.bet) return;
            state.setBalance(state.balance - state.bet);
            state.setWinAmount(0);
            this.startRound();
        } else if (this.phase === 'playing' && this.picks > 0) {
            this.cashOut();
        }
    }

    private startRound(): void {
        this.phase = 'playing';
        this.picks = 0;
        this.bombs.clear();
        while (this.bombs.size < this.mines) this.bombs.add((Math.random() * CELLS) | 0);
        for (const t of this.tiles) {
            t.isBomb = this.bombs.has(t.index);
            this.setFrontArt(t);
            if (t.revealed) this.flipDown(t);
        }
        this.styleAction(0x232a3a, 0x3a4663, 'CASH OUT', 'pick a gem first');
        this.updateHeader();
    }

    private pick(t: TileCell): void {
        if (this.phase !== 'playing' || t.revealed) return;
        t.revealed = true;
        if (t.isBomb) {
            this.bust(t);
            return;
        }
        this.picks++;
        this.flipUp(t, 0, () => {
            const c = this.tileCenter(t.index);
            this.sparkleBurst(c.x, c.y);
        });
        const state = gameStore.getState();
        const current = fairMult(this.picks, this.mines);
        this.styleAction(0x28a909, 0x5be32a, 'CASH OUT', `$${Math.floor(state.bet * current)}`);
        this.updateHeader();
        if (this.picks >= CELLS - this.mines) this.cashOut(); // cleared every gem
    }

    private cashOut(): void {
        const state = gameStore.getState();
        const mult = fairMult(this.picks, this.mines);
        const win = Math.floor(state.bet * mult);
        state.setBalance(state.balance + win);
        state.setWinAmount(win);
        this.phase = 'done';
        this.revealRemaining(0.35);
        this.styleAction(0x28a909, 0x5be32a, 'BANKED', `$${win} @ ${mult.toFixed(2)}x`);
        this.showBanner(`+$${win}`, 0x7dffb0);
        const c = this.tileCenter(12);
        this.coinFountain(c.x, c.y, Math.min(34, 10 + this.picks * 3));
        gsap.delayedCall(1.6, () => this.resetRound());
    }

    private bust(t: TileCell): void {
        this.phase = 'done';
        this.flipUp(t, 0, () => {
            const c = this.tileCenter(t.index);
            this.explosion(c.x, c.y);
        });
        // Chain-reveal the other bombs.
        let i = 1;
        for (const other of this.tiles) {
            if (other === t || !other.isBomb || other.revealed) continue;
            other.revealed = true;
            this.flipUp(other, 0.1 + i * 0.07);
            i++;
        }
        this.revealRemaining(0.65);
        this.shake(18);
        gsap.killTweensOf(this.redFlash);
        gsap.timeline()
            .set(this.redFlash, { alpha: 0.3 })
            .to(this.redFlash, { alpha: 0, duration: 0.7, ease: 'power2.out' });
        this.styleAction(0x5a1020, 0xff4d6d, 'BUSTED', `lost $${gameStore.getState().bet}`);
        this.showBanner('BOOM!', 0xff4d6d);
        gsap.delayedCall(2.0, () => this.resetRound());
    }

    private resetRound(): void {
        this.phase = 'idle';
        this.picks = 0;
        for (const t of this.tiles) if (t.revealed) this.flipDown(t);
        this.styleAction(0x0e7c8a, 0x6fe9ff, 'START', `bet $${gameStore.getState().bet}`);
        this.updateHeader();
    }

    /** Ghost-reveal everything left unturned at round end (dimmed). */
    private revealRemaining(alpha: number): void {
        for (const t of this.tiles) {
            if (t.revealed) continue;
            t.revealed = true;
            this.flipUp(t, 0.3 + Math.random() * 0.3);
            t.root.alpha = alpha;
        }
    }

    // --- grid ------------------------------------------------------------------

    private tileCenter(index: number): { x: number; y: number } {
        const col = index % GRID;
        const row = (index / GRID) | 0;
        return {
            x: this.gridX + col * (TILE + GAP) + TILE / 2,
            y: this.gridY + row * (TILE + GAP) + TILE / 2,
        };
    }

    private buildGrid(): void {
        // Stone well behind the grid.
        const w = GRID * TILE + (GRID - 1) * GAP;
        this.gridLayer.addChild(new Graphics()
            .roundRect(this.gridX - 26, this.gridY - 26, w + 52, w + 52, 30).fill({ color: 0x0a121f, alpha: 0.88 })
            .roundRect(this.gridX - 26, this.gridY - 26, w + 52, w + 52, 30).stroke({ width: 4, color: 0x37c4de, alpha: 0.7 })
            .roundRect(this.gridX - 14, this.gridY - 14, w + 28, w + 28, 22).stroke({ width: 2, color: 0x7af2ff, alpha: 0.3 }));

        for (let i = 0; i < CELLS; i++) {
            const c = this.tileCenter(i);
            const root = new Container();
            root.position.set(c.x, c.y);

            const back = this.makeArt('m_tile', 0x2c3c52);
            const front = new Container(); // filled per-round by setFrontArt
            front.visible = false;
            root.addChild(back, front);

            root.eventMode = 'static';
            root.cursor = 'pointer';
            const tile: TileCell = { root, back, front, revealed: false, isBomb: false, index: i };
            root.on('pointerover', () => {
                if (this.phase === 'playing' && !tile.revealed) gsap.to(root.scale, { x: 1.06, y: 1.06, duration: 0.15 });
            });
            root.on('pointerout', () => {
                if (!tile.revealed) gsap.to(root.scale, { x: 1, y: 1, duration: 0.15 });
            });
            root.on('pointerdown', () => this.pick(tile));

            this.tiles.push(tile);
            this.gridLayer.addChild(root);
        }
    }

    /** Sprite from generated art, or a procedural stand-in if the PNG is missing. */
    private makeArt(id: string, fallback: number): Container {
        const c = new Container();
        const tex = this.textures.get(id);
        if (tex) {
            const s = new Sprite(tex);
            s.anchor.set(0.5);
            s.width = TILE;
            s.height = TILE;
            c.addChild(s);
        } else {
            c.addChild(new Graphics()
                .roundRect(-TILE / 2, -TILE / 2, TILE, TILE, 18).fill(fallback)
                .roundRect(-TILE / 2, -TILE / 2, TILE, TILE, 18).stroke({ width: 3, color: 0xd4af37 }));
        }
        return c;
    }

    private setFrontArt(t: TileCell): void {
        t.front.removeChildren().forEach((c) => c.destroy({ children: true }));
        const art = this.makeArt(t.isBomb ? 'm_bomb' : 'm_gem', t.isBomb ? 0x22262e : 0x0fbf6f);
        if (!t.isBomb) art.filters = [this.gemGlow];
        t.front.addChild(art);
    }

    /** 3D card flip: back edge-on → swap → front snaps open. */
    private flipUp(t: TileCell, delay: number, onOpen?: () => void): void {
        gsap.killTweensOf(t.back.scale);
        gsap.killTweensOf(t.front.scale);
        gsap.timeline({ delay })
            .to(t.back.scale, { x: 0, duration: 0.13, ease: 'power2.in' })
            .add(() => {
                t.back.visible = false;
                t.front.visible = true;
                t.front.scale.x = 0;
                onOpen?.();
            })
            .to(t.front.scale, { x: 1, duration: 0.2, ease: 'back.out(2)' })
            .fromTo(t.root.scale, { x: 1.1, y: 1.1 }, { x: 1, y: 1, duration: 0.3, ease: 'back.out(2)' }, '<');
    }

    private flipDown(t: TileCell): void {
        t.revealed = false;
        t.root.alpha = 1;
        gsap.killTweensOf(t.back.scale);
        gsap.killTweensOf(t.front.scale);
        gsap.timeline()
            .to(t.front.scale, { x: 0, duration: 0.11, ease: 'power2.in' })
            .add(() => {
                t.front.visible = false;
                t.back.visible = true;
                t.back.scale.x = 0;
            })
            .to(t.back.scale, { x: 1, duration: 0.16, ease: 'back.out(1.8)' });
    }

    // --- effects ------------------------------------------------------------------

    private star(g: Graphics, r: number, color: number): void {
        const pts: number[] = [];
        for (let i = 0; i < 8; i++) {
            const rad = i % 2 === 0 ? r : r * 0.4;
            const a = (Math.PI * i) / 4 - Math.PI / 2;
            pts.push(Math.cos(a) * rad, Math.sin(a) * rad);
        }
        g.poly(pts).fill({ color });
    }

    private sparkleBurst(x: number, y: number): void {
        for (let i = 0; i < 7; i++) {
            let s = this.sparkles.find((g) => !g.visible);
            if (!s) {
                s = new Graphics();
                s.blendMode = 'add';
                s.visible = false;
                this.fxLayer.addChild(s);
                this.sparkles.push(s);
            }
            s.clear();
            this.star(s, 7 + Math.random() * 9, i % 2 === 0 ? 0x7dffb0 : 0xffffff);
            s.position.set(x, y);
            s.alpha = 1;
            s.rotation = Math.random() * Math.PI;
            s.visible = true;
            const a = Math.random() * Math.PI * 2;
            const d = 40 + Math.random() * 80;
            gsap.killTweensOf(s);
            gsap.to(s, {
                x: x + Math.cos(a) * d, y: y + Math.sin(a) * d, alpha: 0, rotation: s.rotation + 2,
                duration: 0.55 + Math.random() * 0.3, ease: 'power2.out',
                onComplete: () => { s.visible = false; },
            });
        }
    }

    private explosion(x: number, y: number): void {
        for (let i = 0; i < 30; i++) {
            let p = this.boomParts.find((g) => !g.visible);
            if (!p) {
                p = new Graphics();
                p.blendMode = 'add';
                p.visible = false;
                this.fxLayer.addChild(p);
                this.boomParts.push(p);
            }
            const colors = [0xffd54f, 0xff8a3d, 0xff4d6d, 0xfff3d0];
            p.clear().circle(0, 0, 4 + Math.random() * 10).fill({ color: colors[i % colors.length] });
            p.position.set(x, y);
            p.alpha = 1;
            p.visible = true;
            const a = Math.random() * Math.PI * 2;
            const speed = 100 + Math.random() * 360;
            gsap.killTweensOf(p);
            gsap.to(p, {
                x: x + Math.cos(a) * speed * 0.6,
                y: y + Math.sin(a) * speed * 0.6 + 50,
                alpha: 0,
                duration: 0.6 + Math.random() * 0.5,
                ease: 'power2.out',
                onComplete: () => { p.visible = false; },
            });
        }
    }

    private coinFountain(x: number, y: number, count: number): void {
        for (let i = 0; i < count; i++) {
            let c = this.coins.find((g) => !g.visible);
            if (!c) {
                c = new Graphics();
                c.visible = false;
                this.fxLayer.addChild(c);
                this.coins.push(c);
            }
            const size = 7 + Math.random() * 8;
            c.clear()
                .ellipse(0, 0, size, size * 0.8).fill({ color: 0xffd54f })
                .ellipse(0, 0, size, size * 0.8).stroke({ width: 2, color: 0x8a6512 });
            c.position.set(x, y);
            c.alpha = 1;
            c.visible = true;
            const a = -Math.PI / 2 + (Math.random() - 0.5) * 1.6;
            const speed = 300 + Math.random() * 380;
            gsap.killTweensOf(c);
            gsap.killTweensOf(c.scale);
            gsap.to(c, {
                x: x + Math.cos(a) * speed * 0.6,
                y: y + Math.sin(a) * speed * 0.6 + 430,
                alpha: 0,
                duration: 1.0 + Math.random() * 0.5,
                delay: Math.random() * 0.25,
                ease: 'power1.in',
                onComplete: () => { c.visible = false; },
            });
            gsap.to(c.scale, { x: 0.3, duration: 0.2, yoyo: true, repeat: 7, ease: 'sine.inOut' });
        }
    }

    private shake(amplitude: number): void {
        gsap.killTweensOf(this.position);
        const tl = gsap.timeline({ onComplete: () => this.position.set(0, 0) });
        for (let i = 0; i < 6; i++) {
            const falloff = 1 - i / 7;
            tl.to(this.position, {
                x: (Math.random() - 0.5) * 2 * amplitude * falloff,
                y: (Math.random() - 0.5) * 2 * amplitude * falloff,
                duration: 0.05,
            });
        }
        tl.to(this.position, { x: 0, y: 0, duration: 0.06 });
    }

    private showBanner(msg: string, tint: number): void {
        this.banner.text = msg;
        this.banner.style.fill = tint;
        this.banner.alpha = 1;
        this.banner.visible = true;
        gsap.killTweensOf(this.banner);
        gsap.killTweensOf(this.banner.scale);
        gsap.fromTo(this.banner.scale, { x: 0.3, y: 0.3 }, { x: 1, y: 1, duration: 0.45, ease: 'back.out(2.2)' });
        gsap.to(this.banner, { alpha: 0, duration: 0.5, delay: 1.4, onComplete: () => { this.banner.visible = false; } });
    }

    // --- presentation ----------------------------------------------------------------

    private async buildBackground(): Promise<Container> {
        const env = new Container();
        const W = GameConfig.width;
        const H = GameConfig.height;
        const tex = await AssetManager.loadFirstTexture(['mines-bg.png']);
        if (tex) {
            const bg = new Sprite(tex);
            bg.width = W;
            bg.height = H;
            env.addChild(bg);
        } else {
            env.addChild(new Graphics().rect(0, 0, W, H).fill(new FillGradient({
                type: 'linear', start: { x: 0, y: 0 }, end: { x: 0, y: 1 }, textureSpace: 'local',
                colorStops: [{ offset: 0, color: 0x101a30 }, { offset: 1, color: 0x04060c }],
            })));
        }

        const title = new Text({
            text: 'CRYSTAL MINES',
            style: {
                fontFamily: '"Arial Black", Impact, sans-serif', fontSize: 44, fontWeight: '900', letterSpacing: 7,
                fill: 0x7dffb0, stroke: { color: 0x04200f, width: 6 },
                dropShadow: { color: 0x35d07f, blur: 12, distance: 0, alpha: 0.7 },
            },
        });
        title.anchor.set(0, 0.5);
        title.position.set(44, 52);
        env.addChild(title);

        this.redFlash = new Graphics().rect(0, 0, W, H).fill(0xff2440);
        this.redFlash.alpha = 0;
        env.addChild(this.redFlash);
        return env;
    }

    private createUI(): void {
        const W = GameConfig.width;
        const H = GameConfig.height;

        // Header: gems found · current · next multiplier.
        this.headerText = new Text({
            text: '',
            style: { fontFamily: '"Arial Black", Impact, sans-serif', fontSize: 30, fontWeight: '900', letterSpacing: 2, fill: 0xd7ffe9, stroke: { color: 0x04200f, width: 5 } },
        });
        this.headerText.anchor.set(0.5);
        this.headerText.position.set(W / 2, 112);
        this.uiContainer.addChild(this.headerText);

        // Centre banner (BOOM! / +$N).
        this.banner = new Text({
            text: '',
            style: { fontFamily: '"Arial Black", Impact, sans-serif', fontSize: 120, fontWeight: '900', fill: 0x7dffb0, stroke: { color: 0x04140a, width: 12 } },
        });
        this.banner.anchor.set(0.5);
        this.banner.position.set(W / 2, 520);
        this.banner.visible = false;
        this.uiContainer.addChild(this.banner);

        // --- bottom control panel ---
        const panelW = 980;
        const panelH = 124;
        const panelX = W / 2 - panelW / 2;
        const panelY = H - panelH - 22;
        this.uiContainer.addChild(new Graphics()
            .roundRect(panelX, panelY, panelW, panelH, 26).fill({ color: 0x0c1422, alpha: 0.95 })
            .roundRect(panelX, panelY, panelW, panelH, 26).stroke({ width: 2, color: 0x2a4a6a }));

        // Mines selector pills.
        const minesLabel = new Text({ text: 'MINES', style: { fontFamily: '"Arial Black", Impact, sans-serif', fontSize: 18, fontWeight: '900', letterSpacing: 2, fill: 0x5a8a74 } });
        minesLabel.anchor.set(0.5);
        minesLabel.position.set(panelX + 150, panelY + 28);
        this.uiContainer.addChild(minesLabel);
        MINE_CHOICES.forEach((value, i) => {
            const pill = new Graphics();
            pill.position.set(panelX + 70 + i * 82, panelY + 76);
            pill.eventMode = 'static';
            pill.cursor = 'pointer';
            const label = new Text({ text: `${value}`, style: { fontFamily: '"Arial Black", Impact, sans-serif', fontSize: 24, fontWeight: '900', fill: 0xffffff } });
            label.anchor.set(0.5);
            pill.addChild(label);
            this.stylePill(pill, label, value === this.mines);
            pill.on('pointerdown', () => {
                if (this.phase === 'playing') { this.shake(5); return; }
                this.mines = value;
                for (const mp of this.minePills) this.stylePill(mp.pill, mp.label, mp.value === value);
                this.updateHeader();
            });
            this.uiContainer.addChild(pill);
            this.minePills.push({ pill, label, value });
        });

        // Bet stepper.
        const betLabel = new Text({ text: 'BET', style: { fontFamily: '"Arial Black", Impact, sans-serif', fontSize: 18, fontWeight: '900', letterSpacing: 2, fill: 0x5a8a74 } });
        betLabel.anchor.set(0.5);
        betLabel.position.set(panelX + 460, panelY + 28);
        this.uiContainer.addChild(betLabel);
        this.betValueText = new Text({ text: `$${gameStore.getState().bet}`, style: { fontFamily: '"Arial Black", Impact, sans-serif', fontSize: 36, fontWeight: '900', fill: 0xffffff } });
        this.betValueText.anchor.set(0.5);
        this.betValueText.position.set(panelX + 460, panelY + 76);
        this.uiContainer.addChild(this.betValueText);
        const stepBtn = (dx: number, glyph: string, dir: number): void => {
            const b = new Graphics()
                .circle(0, 0, 24).fill({ color: 0x1a2a3e })
                .circle(0, 0, 24).stroke({ width: 2, color: 0x2a4a6a });
            b.position.set(panelX + 460 + dx, panelY + 76);
            b.eventMode = 'static';
            b.cursor = 'pointer';
            b.on('pointerdown', () => {
                if (this.phase === 'playing') return;
                gsap.fromTo(b.scale, { x: 0.85, y: 0.85 }, { x: 1, y: 1, duration: 0.25, ease: 'back.out(3)' });
                const state = gameStore.getState();
                const i = BET_STEPS.findIndex((v) => v >= state.bet);
                const next = BET_STEPS[Math.max(0, Math.min(BET_STEPS.length - 1, (i < 0 ? BET_STEPS.length - 1 : i) + dir))];
                state.setBet(next);
                this.betValueText.text = `$${next}`;
                if (this.phase === 'idle') this.styleAction(0x0e7c8a, 0x6fe9ff, 'START', `bet $${next}`);
            });
            const t = new Text({ text: glyph, style: { fontFamily: '"Arial Black", Impact, sans-serif', fontSize: 26, fontWeight: '900', fill: 0x8fb8d8 } });
            t.anchor.set(0.5);
            b.addChild(t);
            this.uiContainer.addChild(b);
        };
        stepBtn(-92, '−', -1);
        stepBtn(92, '+', 1);

        // Morphing action button.
        this.actionButton = new Graphics();
        this.actionButton.position.set(panelX + panelW - 200, panelY + panelH / 2);
        this.actionButton.eventMode = 'static';
        this.actionButton.cursor = 'pointer';
        this.actionButton.on('pointerdown', () => {
            gsap.fromTo(this.actionButton.scale, { x: 0.94, y: 0.94 }, { x: 1, y: 1, duration: 0.3, ease: 'back.out(3)' });
            this.action();
        });
        this.actionLabel = new Text({ text: '', style: { fontFamily: '"Arial Black", Impact, sans-serif', fontSize: 32, fontWeight: '900', fill: 0xffffff } });
        this.actionLabel.anchor.set(0.5);
        this.actionLabel.position.set(0, -14);
        this.actionSub = new Text({ text: '', style: { fontFamily: '"Arial Black", Impact, sans-serif', fontSize: 20, fontWeight: '900', fill: 0xffffff } });
        this.actionSub.alpha = 0.85;
        this.actionSub.anchor.set(0.5);
        this.actionSub.position.set(0, 22);
        this.actionButton.addChild(this.actionLabel, this.actionSub);
        this.uiContainer.addChild(this.actionButton);

        this.balanceText = new Text({ text: '', style: { fill: 0x9fd8c0, fontSize: 26 } });
        this.balanceText.position.set(panelX + 8, panelY - 38);
        this.uiContainer.addChild(this.balanceText);

        const back = new Text({ text: '‹ MENU', style: { fill: 0x7dffb0, fontSize: 26, fontWeight: 'bold' } });
        back.position.set(44, 86);
        back.eventMode = 'static';
        back.cursor = 'pointer';
        back.on('pointerdown', () => SceneManager.switchScene(new MenuScene()));
        // (back-to-menu removed) this.uiContainer.addChild(back);

        const hint = new Text({ text: 'START · pick tiles for gems · cash out before a bomb (space = start / cash out)', style: { fill: 0x5a8a74, fontSize: 18, fontStyle: 'italic' } });
        hint.anchor.set(0.5);
        hint.position.set(W / 2, H - 8);
        this.uiContainer.addChild(hint);

        const render = (s: ReturnType<typeof gameStore.getState>): void => {
            this.balanceText.text = `Balance: $${Math.round(s.balance * 100) / 100}`;
        };
        render(gameStore.getState());
        gameStore.subscribe(render);
    }

    private updateHeader(): void {
        if (this.phase === 'playing') {
            const cur = fairMult(this.picks, this.mines);
            const next = fairMult(this.picks + 1, this.mines);
            this.headerText.text = `GEMS ${this.picks}/${CELLS - this.mines}   ·   NOW ${cur.toFixed(2)}x   ·   NEXT ${next.toFixed(2)}x`;
        } else {
            this.headerText.text = `${this.mines} MINES   ·   first pick pays ${fairMult(1, this.mines).toFixed(2)}x`;
        }
    }

    private stylePill(pill: Graphics, label: Text, active: boolean): void {
        pill.clear()
            .roundRect(-34, -22, 68, 44, 22).fill({ color: active ? 0x0e7c8a : 0x101a2c, alpha: active ? 1 : 0.9 })
            .roundRect(-34, -22, 68, 44, 22).stroke({ width: 2.5, color: active ? 0x6fe9ff : 0x2a4a6a });
        label.style.fill = active ? 0xffffff : 0x8fb8d8;
    }

    private styleAction(fill: number, edge: number, label: string, sub: string): void {
        this.actionButton.clear()
            .roundRect(-160, -48, 320, 96, 22).fill(fill)
            .roundRect(-160, -48, 320, 96, 22).stroke({ width: 3, color: edge });
        this.actionLabel.text = label;
        this.actionSub.text = sub;
        this.actionSub.visible = sub.length > 0;
        this.actionLabel.position.set(0, sub ? -14 : 0);
        if (this.actionLabel.width > 280) this.actionLabel.scale.set(280 / this.actionLabel.width);
        else this.actionLabel.scale.set(1);
        if (this.actionSub.width > 280) this.actionSub.scale.set(280 / this.actionSub.width);
        else this.actionSub.scale.set(1);
    }
}
